// instruction_management.c
#include "instruction_management.h"

static instruction_type instruction_types[256] = {
  ONE_BYTE_INSTRUCTION,
  ADDR_11,
  ADDR_16,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  BIT_OFFSET,
  ADDR_11,
  ADDR_16,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  BIT_OFFSET,
  ADDR_11,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  BIT_OFFSET,
  ADDR_11,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  OFFSET,
  ADDR_11,
  DIRECT,
  DIRECT_IMMEDIATE,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  OFFSET,
  ADDR_11,
  DIRECT,
  DIRECT_IMMEDIATE,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  OFFSET,
  ADDR_11,
  DIRECT,
  DIRECT_IMMEDIATE,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  OFFSET,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  IMMEDIATE,
  DIRECT_IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  IMMEDIATE,
  OFFSET,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT_DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  IMMEDIATE_16,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  IMMEDIATE,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  NOT_BIT,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  DIRECT,
  NOT_BIT,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  IMMEDIATE_OFFSET,
  DIRECT_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  IMMEDIATE_OFFSET,
  DIRECT,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ADDR_11,
  BIT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT_OFFSET,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  OFFSET,
  OFFSET,
  OFFSET,
  OFFSET,
  OFFSET,
  OFFSET,
  OFFSET,
  OFFSET,
  ONE_BYTE_INSTRUCTION,
  ADDR_11,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ADDR_11,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  DIRECT,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION,
  ONE_BYTE_INSTRUCTION
};

static char *instructions[256] = {
  "NOP\n",
  "AJMP\t%4.4Xh\n",
  "LJMP\t%4.4Xh\n",
  "RR\t\tA\n",
  "INC\t\tA\n",
  "INC\t\t%s\n",
  "INC\t\t@R0\n",
  "INC\t\t@R1\n",
  "INC\t\tR0\n",
  "INC\t\tR1\n",
  "INC\t\tR2\n",
  "INC\t\tR3\n",
  "INC\t\tR4\n",
  "INC\t\tR5\n",
  "INC\t\tR6\n",
  "INC\t\tR7\n",
  "JBC\t\t%s,\t%2.2Xh\n",
  "ACALL\t%4.4Xh\n",
  "LCALL\t%4.4Xh\n",
  "RRC\t\tA\n",
  "DEC\t\tA\n",
  "DEC\t\t%s\n",
  "DEC\t\t@R0\n",
  "DEC\t\t@R1\n",
  "DEC\t\tR0\n",
  "DEC\t\tR1\n",
  "DEC\t\tR2\n",
  "DEC\t\tR3\n",
  "DEC\t\tR4\n",
  "DEC\t\tR5\n",
  "DEC\t\tR6\n",
  "DEC\t\tR7\n",
  "JB\t\t%s,\t%2.2Xh\n",
  "AJMP\t%4.4Xh\n",
  "RET\n\n",
  "RL\t\tA\n",
  "ADD\t\tA,\t%2.2Xh\n",
  "ADD\t\tA,\t%s\n",
  "ADD\t\tA,\t@R0\n",
  "ADD\t\tA,\t@R1\n",
  "ADD\t\tA,\tR0\n",
  "ADD\t\tA,\tR1\n",
  "ADD\t\tA,\tR2\n",
  "ADD\t\tA,\tR3\n",
  "ADD\t\tA,\tR4\n",
  "ADD\t\tA,\tR5\n",
  "ADD\t\tA,\tR6\n",
  "ADD\t\tA,\tR7\n",
  "JNB\t\t%s,\t%2.2Xh\n",
  "ACALL\t%4.4Xh\n",
  "RETI\n\n",
  "RLC\t\tA\n",
  "ADDC\tA,\t%2.2Xh\n",
  "ADDC\tA,\t%s\n",
  "ADDC\tA,\t@R0\n",
  "ADDC\tA,\t@R1\n",
  "ADDC\tA,\tR0\n",
  "ADDC\tA,\tR1\n",
  "ADDC\tA,\tR2\n",
  "ADDC\tA,\tR3\n",
  "ADDC\tA,\tR4\n",
  "ADDC\tA,\tR5\n",
  "ADDC\tA,\tR6\n",
  "ADDC\tA,\tR7\n",
  "JC\t\t%2.2Xh\n",
  "AJMP\t%4.4Xh\n",
  "ORL\t\t%s,\tA\n",
  "ORL\t\t%s,\t%2.2Xh\n",
  "ORL\t\tA,\t%2.2Xh\n",
  "ORL\t\tA,\t%s\n",
  "ORL\t\tA,\t@R0\n",
  "ORL\t\tA,\t@R1\n",
  "ORL\t\tA,\tR0\n",
  "ORL\t\tA,\tR1\n",
  "ORL\t\tA,\tR2\n",
  "ORL\t\tA,\tR3\n",
  "ORL\t\tA,\tR4\n",
  "ORL\t\tA,\tR5\n",
  "ORL\t\tA,\tR6\n",
  "ORL\t\tA,\tR7\n",
  "JNC\t\t%2.2Xh\n",
  "ACALL\t%4.4Xh\n",
  "ANL\t\t%s,\tA\n",
  "ANL\t\t%s,\t%2.2Xh\n",
  "ANL\t\tA,\t%2.2Xh\n",
  "ANL\t\tA,\t%s\n",
  "ANL\t\tA,\t@R0\n",
  "ANL\t\tA,\t@R1\n",
  "ANL\t\tA,\tR0\n",
  "ANL\t\tA,\tR1\n",
  "ANL\t\tA,\tR2\n",
  "ANL\t\tA,\tR3\n",
  "ANL\t\tA,\tR4\n",
  "ANL\t\tA,\tR5\n",
  "ANL\t\tA,\tR6\n",
  "ANL\t\tA,\tR7\n",
  "JZ\t\t%2.2Xh\n",
  "AJMP\t%4.4Xh\n",
  "XRL\t\t%s,\tA\n",
  "XRL\t\t%s,\t%2.2Xh\n",
  "XRL\t\tA,\t%2.2Xh\n",
  "XRL\t\tA,\t%s\n",
  "XRL\t\tA,\t@R0\n",
  "XRL\t\tA,\t@R1\n",
  "XRL\t\tA,\tR0\n",
  "XRL\t\tA,\tR1\n",
  "XRL\t\tA,\tR2\n",
  "XRL\t\tA,\tR3\n",
  "XRL\t\tA,\tR4\n",
  "XRL\t\tA,\tR5\n",
  "XRL\t\tA,\tR6\n",
  "XRL\t\tA,\tR7\n",
  "JNZ\t\t%2.2Xh\n",
  "ACALL\t%4.4Xh\n",
  "ORL\t\tC,\t%s\n",
  "JMP\t\t@A+DPTR\n",
  "MOV\t\tA,\t%2.2Xh\n",
  "MOV\t\t%s,\t%2.2Xh\n",
  "MOV\t\t@R0,\t%2.2Xh\n",
  "MOV\t\t@R1,\t%2.2Xh\n",
  "MOV\t\tR0,\t%2.2Xh\n",
  "MOV\t\tR1,\t%2.2Xh\n",
  "MOV\t\tR2,\t%2.2Xh\n",
  "MOV\t\tR3,\t%2.2Xh\n",
  "MOV\t\tR4,\t%2.2Xh\n",
  "MOV\t\tR5,\t%2.2Xh\n",
  "MOV\t\tR6,\t%2.2Xh\n",
  "MOV\t\tR7,\t%2.2Xh\n",
  "SJMP\t%2.2Xh\n",
  "AJMP\t%4.4Xh\n",
  "ANL\t\tC,\t%s\n",
  "MOVC\tA,\t@A+PC\n",
  "DIV\t\tA,\tB\n",
  "MOV\t\t%s,\t%s\n",
  "MOV\t\t%s,\t@R0\n",
  "MOV\t\t%s,\t@R1\n",
  "MOV\t\t%s,\tR0\n",
  "MOV\t\t%s,\tR1\n",
  "MOV\t\t%s,\tR2\n",
  "MOV\t\t%s,\tR3\n",
  "MOV\t\t%s,\tR4\n",
  "MOV\t\t%s,\tR5\n",
  "MOV\t\t%s,\tR6\n",
  "MOV\t\t%s,\tR7\n",
  "MOV\t\tDPTR,\t%4.4Xh\n",
  "ACALL\t%4.4Xh\n",
  "MOV\t\t%s,\tC\n",
  "MOVC\tA,\t@A+DPTR\n",
  "SUBB\tA,\t%2.2Xh\n",
  "SUBB\tA,\t%s\n",
  "SUBB\tA,\t@R0\n",
  "SUBB\tA,\t@R1\n",
  "SUBB\tA,\tR0\n",
  "SUBB\tA,\tR1\n",
  "SUBB\tA,\tR2\n",
  "SUBB\tA,\tR3\n",
  "SUBB\tA,\tR4\n",
  "SUBB\tA,\tR5\n",
  "SUBB\tA,\tR6\n",
  "SUBB\tA,\tR7\n",
  "ORL\t\tC,\t/%s\n",
  "AJMP\t%4.4Xh\n",
  "MOV\t\tC,\t%s\n",
  "INC\t\tDPTR\n",
  "MUL\t\tA,\tB\n",
  "RESERVED\n",
  "MOV\t\t@R0,\t%s\n",
  "MOV\t\t@R1,\t%s\n",
  "MOV\t\tR0,\t%s\n",
  "MOV\t\tR1,\t%s\n",
  "MOV\t\tR2,\t%s\n",
  "MOV\t\tR3,\t%s\n",
  "MOV\t\tR4,\t%s\n",
  "MOV\t\tR5,\t%s\n",
  "MOV\t\tR6,\t%s\n",
  "MOV\t\tR7,\t%s\n",
  "ANL\t\tC,\t/%s\n",
  "ACALL\t%4.4Xh\n",
  "CPL\t\t%s\n",
  "CPL\t\tC\n",
  "CJNE\tA,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE\tA,\t%s,\t%2.2Xh\n",
  "CJNE\t@R0,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE\t@R1,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R0,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R1,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R2,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R3,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R4,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R5,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R6,\t%2.2Xh,\t%2.2Xh\n",
  "CJNE R7,\t%2.2Xh,\t%2.2Xh\n",
  "PUSH\t%s\n",
  "AJMP\t%4.4Xh\n",
  "CLR\t\t%s\n",
  "CLR\t\tC\n",
  "SWAP\tA\n",
  "XCH\t\tA,\t%s\n",
  "XCH\t\tA,\t@R0\n",
  "XCH\t\tA,\t@R1\n",
  "XCH\t\tA,\tR0\n",
  "XCH\t\tA,\tR1\n",
  "XCH\t\tA,\tR2\n",
  "XCH\t\tA,\tR3\n",
  "XCH\t\tA,\tR4\n",
  "XCH\t\tA,\tR5\n",
  "XCH\t\tA,\tR6\n",
  "XCH\t\tA,\tR7\n",
  "POP\t\t%s\n",
  "ACALL\t%4.4Xh\n",
  "SETB\t%s\n",
  "SETB\tC\n",
  "DA\t\tA\n",
  "DJNZ\t%s,\t%2.2Xh\n",
  "XCHD\tA,\t@R0\n",
  "XCHD\tA,\t@R1\n",
  "DJNZ\tR0,\t%2.2Xh\n",
  "DJNZ\tR1,\t%2.2Xh\n",
  "DJNZ\tR2,\t%2.2Xh\n",
  "DJNZ\tR3,\t%2.2Xh\n",
  "DJNZ\tR4,\t%2.2Xh\n",
  "DJNZ\tR5,\t%2.2Xh\n",
  "DJNZ\tR6,\t%2.2Xh\n",
  "DJNZ\tR7,\t%2.2Xh\n",
  "MOVX\tA,\t@DPTR\n",
  "AJMP\t%4.4Xh\n",
  "MOVX\tA,\t@R0\n",
  "MOVX\tA,\t@R1\n",
  "CLR\t\tA\n",
  "MOV\t\tA,\t%s\n",
  "MOV\t\tA,\t@R0\n",
  "MOV\t\tA,\t@R1\n",
  "MOV\t\tA,\tR0\n",
  "MOV\t\tA,\tR1\n",
  "MOV\t\tA,\tR2\n",
  "MOV\t\tA,\tR3\n",
  "MOV\t\tA,\tR4\n",
  "MOV\t\tA,\tR5\n",
  "MOV\t\tA,\tR6\n",
  "MOV\t\tA,\tR7\n",
  "MOVX\t@DPTR,\tA\n",
  "ACALL\t%4.4Xh\n",
  "MOVX\t@R0,\tA\n",
  "MOVX\t@R1,\tA\n",
  "CPL\t\tA\n",
  "MOV\t\t%s,\tA\n",
  "MOV\t\t@R0,\tA\n",
  "MOV\t\t@R1,\tA\n",
  "MOV\t\tR0,\tA\n",
  "MOV\t\tR1,\tA\n",
  "MOV\t\tR2,\tA\n",
  "MOV\t\tR3,\tA\n",
  "MOV\t\tR4,\tA\n",
  "MOV\t\tR5,\tA\n",
  "MOV\t\tR6,\tA\n",
  "MOV\t\tR7,\tA\n"
};

// 0x80..0xFF
static char *SFR[256] = {
  "R0 #0",
  "R1 #0",
  "R2 #0",
  "R3 #0",
  "R4 #0",
  "R5 #0",
  "R6 #0",
  "R7 #0",
  "R8 #0",
  "R0 #1",
  "R1 #1",
  "R2 #1",
  "R3 #1",
  "R4 #1",
  "R5 #1",
  "R6 #1",
  "R7 #1",
  "R8 #1",
  "R0 #2",
  "R1 #2",
  "R2 #2",
  "R3 #2",
  "R4 #2",
  "R5 #2",
  "R6 #2",
  "R7 #2",
  "R8 #2",
  "R0 #3",
  "R1 #3",
  "R2 #3",
  "R3 #3",
  "R4 #3",
  "R5 #3",
  "R6 #3",
  "R7 #3",
  "R8 #3",
  "#24h",
  "#25h",
  "#26h",
  "#27h",
  "#28h",
  "#29h",
  "#2Ah",
  "#2Bh",
  "#2Ch",
  "#2Dh",
  "#2Eh",
  "#2Fh",
  "#30h",
  "#31h",
  "#32h",
  "#33h",
  "#34h",
  "#35h",
  "#36h",
  "#37h",
  "#38h",
  "#39h",
  "#3Ah",
  "#3Bh",
  "#3Ch",
  "#3Dh",
  "#3Eh",
  "#3Fh",
  "#40h",
  "#41h",
  "#42h",
  "#43h",
  "#44h",
  "#45h",
  "#46h",
  "#47h",
  "#48h",
  "#49h",
  "#4Ah",
  "#4Bh",
  "#4Ch",
  "#4Dh",
  "#4Eh",
  "#4Fh",
  "#50h",
  "#51h",
  "#52h",
  "#53h",
  "#54h",
  "#55h",
  "#56h",
  "#57h",
  "#58h",
  "#59h",
  "#5Ah",
  "#5Bh",
  "#5Ch",
  "#5Dh",
  "#5Eh",
  "#5Fh",
  "#60h",
  "#61h",
  "#62h",
  "#63h",
  "#64h",
  "#65h",
  "#66h",
  "#67h",
  "#68h",
  "#69h",
  "#6Ah",
  "#6Bh",
  "#6Ch",
  "#6Dh",
  "#6Eh",
  "#6Fh",
  "#70h",
  "#71h",
  "#72h",
  "#73h",
  "#74h",
  "#75h",
  "#76h",
  "#77h",
  "#78h",
  "#79h",
  "#7Ah",
  "#7Bh",
  "#7Ch",
  "#7Dh",
  "#7Eh",
  "#7Fh",
  "P0",
  "SP",
  "DPL",
  "DPH",
  "DPL1",
  "DPH1",
  "DPS",
  "PCON",
  "TCON",
  "TMOD",
  "TL0",
  "TL1",
  "TH0",
  "TH1",
  "CKCON",
  "#8Fh",
  "P1",
  "EXIF",
  "#92h",
  "#93h",
  "#94h",
  "#95h",
  "CKMOD",
  "#97h",
  "SCON0",
  "SBUF0",
  "#9Ah",
  "#9Bh",
  "#9Ch",
  "ACON",
  "#9Eh",
  "#9Fh",
  "P2",
  "#A1h",
  "#A2h",
  "#A3h",
  "#A4h",
  "#A5h",
  "#A6h",
  "#A7h",
  "IE",
  "SADDR0",
  "SADDR1",
  "#ABh",
  "#ACh",
  "#ADh",
  "#AEh",
  "#AFh",
  "P3",
  "IP1",
  "#B2h",
  "#B3h",
  "#B4h",
  "#B5h",
  "#B6h",
  "#B7h",
  "IP0",
  "SADEN0",
  "SADEN1",
  "#BBh",
  "#BCh",
  "#BDh",
  "#BEh",
  "#BFh",
  "SCON1",
  "SBUF1",
  "ROMSIZE",
  "#C3h",
  "PMR",
  "STATUS",
  "#C6h",
  "TA",
  "T2CON",
  "T2MOD",
  "RCAP2L",
  "RCAP2H",
  "TL2",
  "TH2",
  "#CEh",
  "#CFh",
  "PSW",
  "#D1h",
  "#D2h",
  "#D3h",
  "#D4h",
  "FCNTL",
  "FDATA",
  "#D7h",
  "WDCON",
  "#D9h",
  "#DAh",
  "#DBh",
  "#DCh",
  "#DDh",
  "#DEh",
  "#DFh",
  "A",
  "#E1h",
  "#E2h",
  "#E3h",
  "#E4h",
  "#E5h",
  "#E6h",
  "#E7h",
  "EIE",
  "#E9h",
  "#EAh",
  "#EBh",
  "#ECh",
  "#EDh",
  "#EEh",
  "#EFh",
  "B",
  "EIP1",
  "#F2h",
  "#F3h",
  "#F4h",
  "#F5h",
  "#F6h",
  "#F7h",
  "EIP0",
  "#F9h",
  "#FAh",
  "#FBh",
  "#FCh",
  "#FDh",
  "#FEh",
  "#FFh"
};

// BIT Registers
// 0x80..0xFF
static char *SBIT[256] = {
  "00h",
  "01h",
  "02h",
  "03h",
  "04h",
  "05h",
  "06h",
  "07h",
  "08h",
  "09h",
  "0Ah",
  "0Bh",
  "0Ch",
  "0Dh",
  "0Eh",
  "0Fh",
  "10h",
  "11h",
  "12h",
  "13h",
  "14h",
  "15h",
  "16h",
  "17h",
  "18h",
  "19h",
  "1Ah",
  "1Bh",
  "1Ch",
  "1Dh",
  "1Eh",
  "1Fh",
  "20h",
  "21h",
  "22h",
  "23h",
  "24h",
  "25h",
  "26h",
  "27h",
  "28h",
  "29h",
  "2Ah",
  "2Bh",
  "2Ch",
  "2Dh",
  "2Eh",
  "2Fh",
  "30h",
  "31h",
  "32h",
  "33h",
  "34h",
  "35h",
  "36h",
  "37h",
  "38h",
  "39h",
  "3Ah",
  "3Bh",
  "3Ch",
  "3Dh",
  "3Eh",
  "3Fh",
  "40h",
  "41h",
  "42h",
  "43h",
  "44h",
  "45h",
  "46h",
  "47h",
  "48h",
  "49h",
  "4Ah",
  "4Bh",
  "4Ch",
  "4Dh",
  "4Eh",
  "4Fh",
  "50h",
  "51h",
  "52h",
  "53h",
  "54h",
  "55h",
  "56h",
  "57h",
  "58h",
  "59h",
  "5Ah",
  "5Bh",
  "5Ch",
  "5Dh",
  "5Eh",
  "5Fh",
  "60h",
  "61h",
  "62h",
  "63h",
  "64h",
  "65h",
  "66h",
  "67h",
  "68h",
  "69h",
  "6Ah",
  "6Bh",
  "6Ch",
  "6Dh",
  "6Eh",
  "6Fh",
  "70h",
  "71h",
  "72h",
  "73h",
  "74h",
  "75h",
  "76h",
  "77h",
  "78h",
  "79h",
  "7Ah",
  "7Bh",
  "7Ch",
  "7Dh",
  "7Eh",
  "7Fh",

  // P0 (0x80)
  "P0_0",
  "P0_1",
  "P0_2",
  "P0_3",
  "P0_4",
  "P0_5",
  "P0_6",
  "P0_7",

  // TCON (0x88)
  "IT0",
  "IE0",
  "IT1",
  "IE1",
  "TR0",
  "TF0",
  "TR1",
  "TF1",

  // P1 (0x90)
  "P1_0",
  "P1_1",
  "P1_2",
  "P1_3",
  "P1_4",
  "P1_5",
  "P1_6",
  "P1_7",

  // SCON0 (0x98)
  "RI_0",
  "TI_0",
  "RB8_0",
  "TB8_0",
  "REN_0",
  "SM2_0",
  "SM1_0",
  "SM0_0",

  // P2 (0xA0)
  "P2_0",
  "P2_1",
  "P2_2",
  "P2_3",
  "P2_4",
  "P2_5",
  "P2_6",
  "P2_7",

  // IE (0xA8)
  "EX0",
  "ET0",
  "EX1",
  "ET1",
  "ES0",
  "ET2",
  "ES1",
  "EA",

  // P3 (0xB0)
  "P3_0",
  "P3_1",
  "P3_2",
  "P3_3",
  "P3_4",
  "P3_5",
  "P3_6",
  "P3_7",

  // IP0 (0xB8)
  "LPX0",
  "LPT0",
  "LPX1",
  "LPT1",
  "LPS0",
  "LPT2",
  "LPS1",

  "BFh",

  // SCON1 (0xC0)
  "RI_1",
  "TI_1",
  "RB8_1",
  "TB8_1",
  "REN_1",
  "SM2_1",
  "SM1_1",
  "SM0_1",

  // T2CON (0xC8)
  "CP_RL_2",
  "C_T_2",
  "TR_2",
  "EXEN_2",
  "TCLK",
  "RCLK",
  "EXF_2",
  "TF_2",

  // PSW (0xD0)
  "PARITY",
  "F1",
  "OV",
  "RS0",
  "RS1",
  "F0",
  "AC",
  "CY",

  // WDCON (0xD8)
  "RWT",
  "EWT",
  "WTRF",
  "WDIF",
  "PFI",
  "EPFI",
  "POR",
  "SMOD_1",

  "E0h",
  "E1h",
  "E2h",
  "E3h",
  "E4h",
  "E5h",
  "E6h",
  "E7h",

  // EIE (0xE8)
  "EX2",
  "EX3",
  "EX4",
  "EX5",
  "EWDI",

  "EDh",
  "EEh",
  "EFh",
  "F0h",
  "F1h",
  "F2h",
  "F3h",
  "F4h",
  "F5h",
  "F6h",
  "F7h",

  // EIP0 (0xF8)
  "LPX2",
  "LPX3",
  "LPX4",
  "LPX5",
  "LPWDI",

  "FDh",
  "FEh",
  "FFh"
};

unsigned short int bytes_to_word(unsigned char byte1, unsigned char byte0) {
  return ((unsigned short int)byte1 << 8) + (unsigned short int)byte0;
}

static inline unsigned short int addr11_to_addr16(record *record) {
  return ((record->address + 2) & 0xF800) + ((record->bytecode[0] & 0x00E0) << 3) + record->bytecode[1];
}

static unsigned char instruction_size(unsigned char bytecode) {
  instruction_type type = instruction_types[bytecode];
  switch (type) {
    case ONE_BYTE_INSTRUCTION: return 1;
    case ADDR_11:
    case DIRECT:
    case IMMEDIATE:
    case OFFSET:
    case BIT:
    case NOT_BIT: return 2;
    case ADDR_16:
    case IMMEDIATE_16:
    case BIT_OFFSET:
    case DIRECT_IMMEDIATE:
    case DIRECT_DIRECT:
    case IMMEDIATE_OFFSET:
    case DIRECT_OFFSET: return 3;
    default: return 0;
  }
}

void print_instruction(record *records) {
  unsigned char *bytecode = records->bytecode;
  printf("%4.4Xh\t", records->address);

  for (unsigned short int i = 0; i < 4; i++) {
    if (i < records->size) printf("%2.2X ", records->bytecode[i]);
    else printf("   ");
  }

  switch (instruction_types[(unsigned char)records->bytecode[0]]) {
    case ONE_BYTE_INSTRUCTION:
      printf(instructions[bytecode[0]]);
      break;
    case ADDR_11:
      printf(instructions[bytecode[0]], addr11_to_addr16(records));
      break;
    case DIRECT:
      printf(instructions[bytecode[0]], SFR[bytecode[1]]);
      break;
    case IMMEDIATE:
    case OFFSET:
      printf(instructions[bytecode[0]], bytecode[1]);
      break;
    case BIT:
    case NOT_BIT:
      printf(instructions[bytecode[0]], SBIT[bytecode[1]]);
      break;
    case ADDR_16:
    case IMMEDIATE_16:
      printf(instructions[bytecode[0]], bytes_to_word(bytecode[1], bytecode[2]));
      break;
    case BIT_OFFSET:
      printf(instructions[bytecode[0]], SBIT[bytecode[1]], bytecode[2]);
      break;
    case DIRECT_DIRECT:
      printf(instructions[bytecode[0]], SFR[bytecode[1]], SFR[bytecode[2]]);
      break;
    case IMMEDIATE_OFFSET:
      printf(instructions[bytecode[0]], bytecode[1], bytecode[2]);
      break;
    case DIRECT_IMMEDIATE:
    case DIRECT_OFFSET:
      printf(instructions[bytecode[0]], SFR[bytecode[1]], bytecode[2]);
  }
}

void copy_bytes(unsigned char *destination, unsigned char *source, unsigned short int size) {
  for (unsigned short int i = 0; i < size; i++) destination[i] = source[i];
}

static inline record *copy_record_from_offset(record *r1, unsigned short int size, unsigned short int offset, record *r2) {
  unsigned char *bytecode = create_bytevector(size);
  copy_bytes(bytecode, &r1->bytecode[offset], size);
  return create_record(size, r1->address + offset, bytecode, r2);
}

record *extract_instruction(record *r1) {
  record *r2 = NULL;
  unsigned char size;

  if (r1 && (r1->size != ((size = instruction_size(r1->bytecode[0]))))) {
    r2 = copy_record_from_offset(r1, size, 0, copy_record_from_offset(r1, r1->size - size, size, r1->next));
    r1 = destroy_record(r1);
    r1 = r2;
  } return r1;
}
